import 'package:flutter_svg/flutter_svg.dart';

class PryzBasicIcons {
  PryzBasicIcons._();

  static const _bookmarkPath = 'assets/icons/basic/bookmark.svg';
  static const _bookmarksPath = 'assets/icons/basic/bookmarks.svg';
  static const _checkMarkPath = 'assets/icons/basic/check-mark.svg';
  static const _eyePath = 'assets/icons/basic/eye.svg';
  static const _eyeNoPath = 'assets/icons/basic/eye-no.svg';
  static const _globePath = 'assets/icons/basic/globe.svg';
  static const _globeNoPath = 'assets/icons/basic/globe-no.svg';
  static const _heartPath = 'assets/icons/basic/heart.svg';
  static const _heartNoPath = 'assets/icons/basic/heart-no.svg';
  static const _homePath = 'assets/icons/basic/home.svg';
  static const _inboxPath = 'assets/icons/basic/inbox.svg';
  static const _moreHorizontalPath = 'assets/icons/basic/more-horizontal.svg';
  static const _moreVerticalPath = 'assets/icons/basic/more-vertical.svg';
  static const _optionsPath = 'assets/icons/basic/options.svg';
  static const _settingsPath = 'assets/icons/basic/settings.svg';
  static const _sharePath = 'assets/icons/basic/share.svg';
  static const _starPath = 'assets/icons/basic/star.svg';
  static const _starNoPath = 'assets/icons/basic/star-no.svg';
  static const _toggleLeftPath = 'assets/icons/basic/toggle-left.svg';
  static const _toggleRightPath = 'assets/icons/basic/toggle-right.svg';
  static const _trashPath = 'assets/icons/basic/trash.svg';
  static const _trashEmptyPath = 'assets/icons/basic/trash-empty.svg';
  static const _checklistPath = 'assets/icons/basic/checklist.svg';
  static const _contactBookPath = 'assets/icons/basic/contact-book.svg';
  static const _circleBlockPath = 'assets/icons/basic/circle-block.svg';
  static const _circleCheckedPath = 'assets/icons/basic/circle-checked.svg';
  static const _circleMinusPath = 'assets/icons/basic/circle-minus.svg';
  static const _circlePlusPath = 'assets/icons/basic/circle-plus.svg';
  static const _circleXPath = 'assets/icons/basic/circle-x.svg';
  static const _menuPath = 'assets/icons/basic/menu.svg';
  static const _menuDotsPath = 'assets/icons/basic/menu-dots.svg';
  static const _minusPath = 'assets/icons/basic/minus.svg';
  static const _plusPath = 'assets/icons/basic/plus.svg';

  static final bookmark = SvgPicture.asset(_bookmarkPath);
  static final bookmarks = SvgPicture.asset(_bookmarksPath);
  static final checkMark = SvgPicture.asset(_checkMarkPath);
  static final eye = SvgPicture.asset(_eyePath);
  static final eyeNo = SvgPicture.asset(_eyeNoPath);
  static final globe = SvgPicture.asset(_globePath);
  static final globeNo = SvgPicture.asset(_globeNoPath);
  static final heart = SvgPicture.asset(_heartPath);
  static final heartNo = SvgPicture.asset(_heartNoPath);
  static final home = SvgPicture.asset(_homePath);
  static final inbox = SvgPicture.asset(_inboxPath);
  static final moreHorizontal = SvgPicture.asset(_moreHorizontalPath);
  static final moreVertical = SvgPicture.asset(_moreVerticalPath);
  static final options = SvgPicture.asset(_optionsPath);
  static final settings = SvgPicture.asset(_settingsPath);
  static final share = SvgPicture.asset(_sharePath);
  static final star = SvgPicture.asset(_starPath);
  static final starNo = SvgPicture.asset(_starNoPath);
  static final toggleLeft = SvgPicture.asset(_toggleLeftPath);
  static final toggleRight = SvgPicture.asset(_toggleRightPath);
  static final trash = SvgPicture.asset(_trashPath);
  static final trashEmpty = SvgPicture.asset(_trashEmptyPath);
  static final checklist = SvgPicture.asset(_checklistPath);
  static final contactBook = SvgPicture.asset(_contactBookPath);
  static final circleBlock = SvgPicture.asset(_circleBlockPath);
  static final circleChecked = SvgPicture.asset(_circleCheckedPath);
  static final circleMinus = SvgPicture.asset(_circleMinusPath);
  static final circlePlus = SvgPicture.asset(_circlePlusPath);
  static final circleX = SvgPicture.asset(_circleXPath);
  static final menu = SvgPicture.asset(_menuPath);
  static final menuDots = SvgPicture.asset(_menuDotsPath);
  static final minus = SvgPicture.asset(_minusPath);
  static final plus = SvgPicture.asset(_plusPath);
}
